### ISSUE TITLE
EX+ skill does not revert when changing from 5* to <5*

### ISSUE THREAD

**Issue by sadeslandes** [Andu2/pricalc#3]
Initial setup
![Initial setup](https://i.imgur.com/zS9NKG2.png)

Change to 5\*
![Set to 5*](https://i.imgur.com/qz3eYOM.png)

Change back to 3\*
![Back to 3*](https://i.imgur.com/lmmE5m3.png)

Upon changing back to 3\* `One-Eyed Devil` is still displaying the 5\* version and stat bonuses are still being applied

**Comment by Andu2** [comment]
Thanks for the report!
I believe this was fixed with commit c3b923d531a38e9741e87dcf2b60324454f72cb1. It seems to be working correctly now.
