### ISSUE TITLE
Skills formulas always rounds up

### ISSUE THREAD

**Issue by MsNyara** [Andu2/pricalc#8]
What the tittle says. This just came when I tried to calculate damage, and I found Makoto's Def Shred at LV93 is indicated as 75 in Pricalc, however the real value, both display in-game, and real in-game damage, is 76, and just thinking a bit more about it, it is kinda obvious, to avoid having values with 0 in the first few levels without having to force a base of 1.

**Comment by Andu2** [comment]
Thanks for the report. It will be nice to have more confidence in the rounding once I start adding more simulator-type features.

**Comment by Andu2** [comment]
Fixed in 95c2621851fc0aa3e4cf257da38871e158ff6545
